import React, { useEffect, useState } from 'react';
import { mockBackend } from '../services/mockBackend';
import { getMarketInsights } from '../services/geminiService';
import { GoldPrice, PriceHistoryPoint } from '../types';
import ReactMarkdown from 'react-markdown';
import { Sparkles, RefreshCw } from 'lucide-react';
import { Button } from '../components/Button';

export const Insights = () => {
  const [analysis, setAnalysis] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [priceData, setPriceData] = useState<{current: GoldPrice, history: PriceHistoryPoint[]} | null>(null);

  const fetchAnalysis = async () => {
    setLoading(true);
    try {
      const current = await mockBackend.getPrice();
      const history = await mockBackend.getPriceHistory();
      setPriceData({ current, history });
      
      const result = await getMarketInsights(current, history);
      setAnalysis(result);
    } catch (e) {
      console.error(e);
      setAnalysis("Unable to retrieve insights at this time.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAnalysis();
  }, []);

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center space-y-4">
        <h2 className="text-4xl font-serif text-transparent bg-clip-text bg-gradient-to-r from-gold-300 to-gold-600">
          AI Market Intelligence
        </h2>
        <p className="text-zinc-400 max-w-xl mx-auto">
            Powered by Google Gemini models, our proprietary algorithms analyze real-time market data to give you the competitive edge.
        </p>
      </div>

      <div className="bg-zinc-900/40 backdrop-blur-md border border-zinc-800 p-8 rounded-2xl relative overflow-hidden min-h-[300px]">
        {/* Decorative elements */}
        <div className="absolute top-0 right-0 p-32 bg-gold-500/5 blur-3xl rounded-full pointer-events-none -mr-16 -mt-16"></div>
        <div className="absolute bottom-0 left-0 p-24 bg-blue-500/5 blur-3xl rounded-full pointer-events-none -ml-16 -mb-16"></div>

        <div className="flex justify-between items-center mb-8 relative z-10">
             <div className="flex items-center gap-3 text-gold-400">
                <Sparkles className="animate-pulse" size={24} />
                <span className="font-medium tracking-wide text-sm uppercase">Latest Report</span>
             </div>
             <Button variant="outline" onClick={fetchAnalysis} isLoading={loading} className="!py-2 !px-4 text-xs">
                <RefreshCw size={14} className="mr-2" />
                Refresh Analysis
             </Button>
        </div>

        <div className="relative z-10">
            {loading ? (
                <div className="space-y-4 animate-pulse">
                    <div className="h-4 bg-zinc-800 rounded w-3/4"></div>
                    <div className="h-4 bg-zinc-800 rounded w-full"></div>
                    <div className="h-4 bg-zinc-800 rounded w-5/6"></div>
                    <div className="h-4 bg-zinc-800 rounded w-2/3"></div>
                </div>
            ) : (
                <div className="prose prose-invert prose-headings:text-gold-200 prose-strong:text-gold-400 prose-p:text-zinc-300 max-w-none">
                    <ReactMarkdown>{analysis}</ReactMarkdown>
                </div>
            )}
        </div>
      </div>

        {/* Disclaimer */}
        <p className="text-xs text-center text-zinc-600">
            * This analysis is generated by AI for simulation purposes only. Do not use for real financial decisions.
        </p>
    </div>
  );
};
